#!/usr/bin/python
# -*- coding: utf-8 -*-
# @date: 20090921
# @author: shell.xu
import logging

import webserver
import actions

ACTION = actions.HttpFileAction ('~/')

if __name__ == "__main__":
    webserver.log = webserver.Logging ("~/access.log", "~/error.log",
                                       level = logging.INFO)
    # webserver.log.hook_std ()
    try:
        server = webserver.HttpServer (ACTION)
        server.listen (port = 8001)
        server.run ()
    except KeyboardInterrupt: log.log.write_stdout ("exit.\r\n")
