Document: pyweb
Title: Debian pyweb Manual
Author: <insert document author here>
Abstract: This manual describes what pyweb is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pyweb/pyweb.sgml.gz

Format: postscript
Files: /usr/share/doc/pyweb/pyweb.ps.gz

Format: text
Files: /usr/share/doc/pyweb/pyweb.text.gz

Format: HTML
Index: /usr/share/doc/pyweb/html/index.html
Files: /usr/share/doc/pyweb/html/*.html


